version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: project_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: some_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./db-data/db:/var/lib/mysql

volumes:
  db-data:
